---
- hosts: bastion
  name: Configure the bastion host
  gather_facts: no
  become: yes
  tasks:
    - name: Change hostname
      tags:
        - hostname
      hostname:
        name: '{{ hostname }}'
      when: hostname is defined

    - name: Change hosts file
      tags:
        - hosts-file
      blockinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        content: |
          127.0.0.1 {{ hostname }}
      when: hostname is defined

    - name: Copy profile configuration
      tags:
        - profile
      copy:
        src: ./files/profile.sh
        dest: /etc/profile.d/profile.sh

    - name: Reboot the server
      tags:
        - profile
      reboot:

    - name: Fix locale issue
      tags:
        - locale
      blockinfile:
        dest: /etc/environment
        block: |
          LANG=en_US.utf-8
          LC_ALL=en_US.utf-8

    - name: Install Ansible dependencies
      apt:
        name: '{{ item }}'
      tags:
        - ansible
      loop:
        - software-properties-common

    - name: Add apt repository
      tags:
        - ansible
      apt_repository:
        repo: 'ppa:ansible/ansible'
        state: present

    - name: Update repository cache
      tags:
        - ansible
      apt:
        update_cache: yes

    - name: Install Ansible
      apt:
        name: '{{ item }}'
      tags:
        - ansible
      loop:
        - ansible

    - name: Copy the ssh private key
      become: no
      tags:
        - ssh
      copy:
        src: '{{ kp_file }}'
        dest: '/home/{{ ansible_ssh_user }}/.ssh/{{kp_name}}'
        mode: 0400
        owner: '{{ ansible_ssh_user }}'
        group: '{{ ansible_ssh_user }}'
    
    - name: Clone the Ansible-OKD repo
      become: no
      tags:
        - ansible
      git:
        repo: 'https://github.com/guzmonne/ansible-okd.git'
        dest: '/home/{{ansible_ssh_user}}/okd'

    - name: Remove vim installation
      tags: spf13
      apt:
        name: vim
        state: absent

    - name: Install vim-nox
      tags: spf13
      apt:
        name: vim-nox
        state: present

    - name: Copy hosts file
      tags:
        - openshift-ansible
      template:
        src: ./files/hosts.j2
        dest: /etc/ansible/hosts
        mode: 0644
      register: verify