---
- hosts: cert_manager
  name: Configure hosts for OKD installation
  vars_files:
    - ./vars/okd.yml
    - ./secret/credentials.yml
  become: yes
  tasks:
    - name: Clone the acme.sh Github repo
      git:
        repo: 'https://github.com/Neilpang/acme.sh.git'
        dest: '/tmp/acme.sh'

    - name: Install acme.sh
      shell: 'cd /tmp/acme.sh && ./acme.sh --install'

    - name: Configure Route53 credentials
      blockinfile:
        dest: /root/.acme.sh/account.conf
        content: |
          AWS_ACCESS_KEY_ID={{ aws_access_key }}
          AWS_SECRET_ACCESS_KEY={{ aws_secret_key }}

    - name: Issue a CERT
      shell: '/root/.acme.sh/acme.sh --issue --dns dns_aws -d {{openshift_master_cluster_public_hostname}}'

    - name: Copy .cer files
      tags: continue
      shell: '/usr/bin/cp /root/.acme.sh/{{ openshift_master_cluster_public_hostname }}/{{ openshift_master_cluster_public_hostname }}.cer /etc/ansible'

    - name: Copy .key files
      tags: continue
      shell: '/usr/bin/cp /root/.acme.sh/{{ openshift_master_cluster_public_hostname }}/{{ openshift_master_cluster_public_hostname }}.key /etc/ansible'

    - name: Copy ca.cer files
      tags: continue
      shell: '/usr/bin/cp /root/.acme.sh/{{ openshift_master_cluster_public_hostname }}/ca.cer /etc/ansible'

    - name: Copy fullchain.cer
      tags: continue
      shell: '/usr/bin/cp /root/.acme.sh/{{ openshift_master_cluster_public_hostname }}/fullchain.cer /etc/ansible'
