---
- name: Add HTTPS to web console
  hosts: okd
  become: yes
  gather_facts: no
  vars_files:
    - ./vars/okd.yml
  tasks:
    - name: Install NGINX
      yum:
        name: '{{item}}'
        update_cache: yes
      loop:
        - epel-release
        - nginx
    - name: Create .well-known folder
      file:
        path: /var/lib/letsencrypt/.well-known
        state: directory
        group: nginx
        mode: "g+s"
    - name: Copy test file
      tags: test
      copy:
        dest: /var/lib/letsencrypt/.well-known/acme-challenge/index.html
        src: ./files/index.html
        group: nginx
        owner: nginx
    - name: Copy letsencrypt snippet
      copy:
        dest: /etc/nginx/snippets/letsencrypt.conf
        src: ./files/letsencrypt.conf
    - name: Copy Nginx comnfiguration file.
      tags: configuration
      copy:
        dest: /etc/nginx/nginx.conf
        src: ./files/nginx.conf
    - name: Copy default configuration
      template:
        dest: '/etc/nginx/conf.d/{{openshift_master_cluster_public_hostname}}.conf'
        src: ./files/default.j2
    - name: Turn the nginx service on.
      tags: service
      systemd:
        name: nginx
        state: reloaded
