---
- name: Add HTTPS to web console
  hosts: okd
  become: yes
  gather_facts: no
  vars_files:
    - ./vars/okd.yml
  tasks:
    - name: Install NGINX
      yum:
        name: '{{item}}'
        update_cache: yes
      loop:
        - epel-release
        - nginx
    - name: Create .well-known folder
      file:
        path: /var/lib/letsencrypt/.well-known
        state: directory
        group: nginx
        mode: "g+s"
    - name: Copy letsencrypt snippet
      copy:
        dest: /etc/nginx/snippets/letsencrypt.conf
        src: ./files/letsencrypt.conf
    - name: Copy default configuration
      template:
        dest: /etc/nginx/conf.d/default
        src: ./files/default.j2
    - name: Turn the nginx service on.
      tags: service
      systemd:
        name: nginx
        state: reloaded
