all:
  children:
    bastion:
      hosts:
        100.27.28.215:
          hostname: bastion
          kp_name: okd_kp
          kp_file: './secret/{{kp_name}}.pem'
          domain: okd.conatest.click
          private_subnet: 172.31.0.0/16
      vars:
        ansible_private_key_file: ./secret/okd_kp.pem
        ansible_user: ubuntu
        ansible_python_interpreter: /usr/bin/python3
    okd:
      hosts:
        'aio-01.okd.conatest.click':
          hostname: okd-01
          master: True
          private_ip: 172.31.44.36
        'aio-02.okd.conatest.click':
          hostname: okd-02
          private_ip: 172.31.41.164
        'aio-03.okd.conatest.click':
          hostname: okd-03
          private_ip: 172.31.47.66
      children:
        cert_manager:
          hosts:
            'aio-01.okd.conatest.click':
      vars:
        ansible_private_key_file: ./secret/okd_kp.pem
        ansible_user: centos
