all:
  children:
    bastion:
      hosts:
        bastion.okd.conatest.click:
          hostname: bastion
          kp_name: okd_kp
          kp_file: './secret/{{kp_name}}.pem'
          domain: okd.conatest.click
          private_subnet: 172.31.0.0/16
      vars:
        ansible_private_key_file: ./secret/okd_kp.pem
        ansible_user: ubuntu
        ansible_python_interpreter: /usr/bin/python3