---
all:
  children:
    OSEv3:
      children:
        masters:
          hosts:
            aio-01.okd.conatest.click:
              openshift_public_ip: 18.212.64.117
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-02.okd.conatest.click:
              openshift_public_ip: 54.144.17.62
              openshift_public_hostname: aio-02-external.okd.conatest.click
            aio-03.okd.conatest.click:
              openshift_public_ip: 54.172.195.34
              openshift_public_hostname: aio-03-external.okd.conatest.click
        nodes:
          hosts:
            aio-01.okd.conatest.click:
              openshift_node_group_name: node-config-all-in-one
              openshift_public_ip: 18.212.64.117
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-02.okd.conatest.click:
              openshift_node_group_name: node-config-all-in-one
              openshift_public_ip: 54.144.17.62
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-03.okd.conatest.click:
              openshift_node_group_name: node-config-all-in-one
              openshift_public_ip: 54.172.195.34
              openshift_public_hostname: aio-03-external.okd.conatest.click
        etcd:
          hosts:
            aio-01.okd.conatest.click:
              openshift_public_ip: 18.212.64.117
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-02.okd.conatest.click:
              openshift_public_ip: 54.144.17.62
              openshift_public_hostname: aio-02-external.okd.conatest.click
            aio-03.okd.conatest.click:
              openshift_public_ip: 54.172.195.34
              openshift_public_hostname: aio-03-external.okd.conatest.click
      vars:
        ansible_ssh_user: centos
        ansible_ssh_private_key_file: /home/ubuntu/.ssh/okd_kp
        ansible_become: true
        # Enable FirewallD
        os_firewall_use_firewalld: true
        # Openshift deployment type
        openshift_deployment_type: origin
        # Disable hardware checks
        openshift_disable_check: disk_availability,memory_availability
        # Set domain and load balancing method
        openshift_master_default_subdomain: okd.conatest.click
        openshift_master_cluster_method: native
        openshift_master_cluster_hostname: internal.okd.conatest.click
        openshift_master_cluster_public_hostname: cluster.okd.conatest.click
        # allow unencrypted connection within cluster
        openshift_docker_insecure_registries: 172.31.0.0/16
        # Configure the certificate validity
        openshift_hosted_registry_cert_expire_days: 1825
        openshift_ca_cert_expire_days: 1825
        openshift_node_cert_expire_days: 1825
        openshift_master_cert_expire_days: 1825
        etcd_ca_default_days: 1825
        # Install the OpenShift catalog
        openshift_enable_service_catalog: True
        # Install the OpenShift Ansible Broker
        ansible_service_broker_install: False
        # Configuring the Template Service Broker
        template_service_broker_install: False
        openshift_master_overwrite_named_certificates: true
        openshift_master_named_certificates:
          - certfile: /etc/ansible/cluster.okd.conatest.click/cluster.okd.conatest.click.crt
            keyfile: /etc/ansible/cluster.okd.conatest.click/cluster.okd.conatest.click.key
            names:
              cluster.okd.conatest.click
        openshift_hosted_router_certificate:
          certfile: /etc/ansible/*.okd.conatest.click/*.okd.conatest.click.crt
          keyfile: /etc/ansible/*.okd.conatest.click/*.okd.conatest.click.key
          cafile: /etc/ansible/*.okd.conatest.click/fullchain.cer
