---
all:
  children:
    OSEv3:
      children:
        masters:
          hosts:
            aio-01.okd.conatest.click:
              openshift_public_ip: 18.212.55.118
              openshift_ip: 172.31.88.139
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-02.okd.conatest.click:
              openshift_public_ip: 54.172.30.214
              openshift_ip: 172.31.95.88
              openshift_public_hostname: aio-02-external.okd.conatest.click
            aio-03.okd.conatest.click:
              openshift_public_ip: 54.196.141.199
              openshift_ip: 172.31.86.119
              openshift_public_hostname: aio-03-external.okd.conatest.click
        nodes:
          hosts:
            aio-01.okd.conatest.click:
              openshift_node_group_name: node-config-all-in-one
              openshift_public_ip: 18.212.55.118
              openshift_ip: 172.31.88.139
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-02.okd.conatest.click:
              openshift_node_group_name: node-config-all-in-one
              openshift_public_ip: 54.172.30.214
              openshift_ip: 172.31.95.88
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-03.okd.conatest.click:
              openshift_node_group_name: node-config-all-in-one
              openshift_public_ip: 54.196.141.199
              openshift_ip: 172.31.86.119
              openshift_public_hostname: aio-03-external.okd.conatest.click
        etcd:
          hosts:
            aio-01.okd.conatest.click:
              openshift_public_ip: 18.212.55.118
              openshift_ip: 172.31.88.139
              openshift_public_hostname: aio-01-external.okd.conatest.click
            aio-02.okd.conatest.click:
              openshift_public_ip: 54.172.30.214
              openshift_ip: 172.31.95.88
              openshift_public_hostname: aio-02-external.okd.conatest.click
            aio-03.okd.conatest.click:
              openshift_public_ip: 54.196.141.199
              openshift_ip: 172.31.86.119
              openshift_public_hostname: aio-03-external.okd.conatest.click
      vars:
        ansible_ssh_user: centos
        ansible_ssh_private_key_file: /home/ubuntu/.ssh/okd_kp
        ansible_become: true
        # Enable FirewallD
        os_firewall_use_firewalld: true
        # Openshift deployment type
        openshift_deployment_type: origin
        # Disable hardware checks
        openshift_disable_check: disk_availability,memory_availability
        # Set domain and load balancing method
        openshift_master_default_subdomain: okd.conatest.click
        openshift_master_cluster_method: native
        openshift_master_cluster_hostname: internal.okd.conatest.click
        openshift_master_cluster_public_hostname: cluster.okd.conatest.click
        # Install the OpenShift catalog
        openshift_enable_service_catalog: True
        # Install the OpenShift Ansible Broker
        ansible_service_broker_install: False
        # Configuring the Template Service Broker
        template_service_broker_install: False
        openshift_master_overwrite_named_certificates: true
        openshift_master_named_certificates:
          - certfile: /etc/ansible/cluster.okd.conatest.click/cluster.okd.conatest.click.cer
            keyfile: /etc/ansible/cluster.okd.conatest.click/cluster.okd.conatest.click.key
            cafile: /etc/ansible/cluster.okd.conatest.click/ca.cer
            names:
              - cluster.okd.conatest.click
        openshift_hosted_router_certificate:
          certfile: /etc/ansible/*.okd.conatest.click/*.okd.conatest.click.cer
          keyfile: /etc/ansible/*.okd.conatest.click/*.okd.conatest.click.key
          cafile: /etc/ansible/*.okd.conatest.click/ca.cer
